(source gnu)
(source melpa)

(depends-on "evil")
(depends-on "evil-commentary")
(depends-on "evil-escape")
(depends-on "evil-exchange")
(depends-on "evil-leader")
(depends-on "evil-matchit")
(depends-on "evil-surround")
(depends-on "evil-visualstar")
(depends-on "pallet")
(depends-on "use-package")
